spring.application.name=transaction-service
#spring.profiles.active=prod

# Database
spring.datasource.url=jdbc:postgresql://localhost:5434/transaction_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA/Hibernate config
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Flyway config
spring.flyway.enabled=true

# Script location for Flyway
spring.flyway.locations=classpath:db/migration