spring.flyway.clean-disabled=true
spring.flyway.schemas=public,impl,spec,api

spring.flyway.url=jdbc:postgresql://localhost:5433/account_db
spring.flyway.user=migration_user
spring.flyway.password=Migrator!User!