spring.flyway.clean-disabled=false
spring.flyway.clean-on-validation-error=true
spring.flyway.schemas=public,impl,spec,api

logging.level.org.springframework.jdbc.core=DEBUG
logging.level.org.springframework.jdbc.core.simple=TRACE