spring.application.name=account-service
spring.profiles.active=dev

# Database
spring.datasource.url=jdbc:postgresql://localhost:5433/account_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA/Hibernate config
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Flyway config
spring.flyway.enabled=true

# Script location for Flyway
spring.flyway.locations=classpath:db/migration

#spring.flyway.repair-on-migrate=true
#spring.flyway.clean-enabled=true
#spring.flyway.clean-on-validation-error=true
#spring.flyway.clean-disabled=false
#spring.flyway.schemas=public,impl,spec,api